web:
    build: .
    command: sh -c 'npm install; npm start'
    ports:
        - '3260:3260'
    volumes: 
        - ./api:/api
    links:
        - 'db:redis'
db:
    image: redis
    ports:
        - '6379:6379'
