web:
    build: .
    command: sh -c 'pip3 install -r requirements.txt; flask run'
    ports:
        - '5000:5000'
    volumes: 
        - .:/api/*
    links:
        - 'db:redis'
db:
    image: redis
    ports:
        - '6379:6379'
    